# Generated by Django 4.1.2 on 2022-10-12 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UniversityClasse',
            new_name='UniversityClasses',
        ),
    ]
