# Generated by Django 4.1.2 on 2022-10-13 21:11

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampusName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Campus_Name', models.CharField(blank=True, default='', max_length=80)),
                ('Campus_ID', models.IntegerField(blank=True, default='')),
                ('State', models.CharField(blank=True, default='', max_length=2)),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
